### ISSUE TITLE
Code and codeblocks should be monospaced

### ISSUE THREAD

**Issue by damaera** [utopian-io/utopian.io#446]
Code blocks are part of the Markdown,
When writing code without monospaced font is very uncomfortable.

Here is when I write in utopian editor
![image](https://user-images.githubusercontent.com/5365957/36847101-cdc41d0a-1d8f-11e8-898a-b80d92868cc4.png)

And here is the preview
![image](https://user-images.githubusercontent.com/5365957/36847108-d3d830e6-1d8f-11e8-853c-ff65eabbf7d2.png)

And here is from someone post
![image](https://user-images.githubusercontent.com/5365957/36847192-181981c4-1d90-11e8-8053-6d190c5c9681.png)

---

It should be like `this`

and like this
```javascript
exports.sourceNodes = async ({ boundActionCreators }) => {
    return;
};
```

**Comment by damaera** [comment]
```css
pre, code {
  font-family: "SFMono-Regular",Consolas,"Liberation Mono",Menlo,Courier,monospace;
}
```
